### ISSUE TITLE
Спрайты

### ISSUE THREAD

**Issue by Tarenokurama** [MindustryDagger/VanillaPlus#12]
![IMG_3797](https://github.com/MindustryDagger/VanillaPlus/assets/161812458/d2666ead-0bd0-43d2-b715-95d67152014c)
Привет, играл с данным модом на андроид и все было почти хорошо, но перейдя на иос столкнулся с такой проблемой, что почти все перестало отображаться, очень неудобно, приходится постоянно искать по названию(

**Comment by MindustryDagger** [comment]
Привет, попробую исправить скоро...

**Comment by Tarenokurama** [comment]
Спасибо ❣️
