### ISSUE TITLE
Предложения по моду

### ISSUE THREAD

**Issue by FJSAGS** [MindustryDagger/VanillaPlus#13]
Привет!
Я поиграл с этим модом в компании (и на некоторых картах) и понял, что некоторые блоки ломают баланс, так что я предлагаю тебе над ними поработать.
Мои предложения.
1. Убрать ВСЕ генераторы ресурсов на энергии. Можно либо повысить их потребление (раз в 10), либо полностью убрать. Банально проще их поставить чем заморачиваться с ресурсами, тем более когда они потребляют меньше энергии чем заводы на ресурсах.
2. Убрать все радужные блоки. Им банально нет применения, тем более выглядят не очень.
3. Уменьшить выработку всех солнечных панелей раза в 3, ведь легче их поставить, чем строить торийки и тд, можно повысить стоимость.
4. Также я не нашел применения новым юнитам, уж извини, но лучше их убрать или доработать.

Критика закончилась, расскажу что можно добавить:

1. Большую катапульту! Очень напрашивается.
2. Еще добывалок спор.
3. Еще один насос (из блоков воды) и один насос из земли.
4. Добавить больше уровней трубопроводов к насосам
6. Новые уровни генераторов электричества (кроме солнечных панелей)
7. Новые уровни крафтеров ресурсов.
8. Большой регенератор и маленький сверхприводный проектор.

Вот и всё по моим предложениям.
Не забывай о балансе!

**Comment by FJSAGS** [comment]
Кстати, могу я сделать ветку в гите чтобы предложить там свои изменения?

**Comment by MindustryDagger** [comment]
можешь)

**Comment by FJSAGS** [comment]
Мне не дает гит делать ветки здесь, так что сделаю форк

**Comment by FJSAGS** [comment]
Итак, спустя пару часов я разобрался. Я поменял потребление всех блоков, теперь они потребляют в 10 раз больше своей обычной версии при обычном выходе.
Также всем генераторам ресурсов (меди, свинца и тд) увеличил потребление в 10 раз, выход не менял. Если потребления не было, то я его не добавлял

**Comment by FJSAGS** [comment]
https://github.com/MindustryDagger/VanillaPlus/pull/15
Вот там большая часть моих изменений

**Comment by Almat2** [comment]
С потреблением в 10 раз перегнул немножно у генераторов обычным генераторам можно и в 3 раза а тем которые могут не встретиться на планете на 5 и тем которые надо изготавливать в 7 раз более чем достаточно. + У тебя маломощьный генератор свинца не работает выдает 0 в мин

**Comment by Almat2** [comment]
Поменяй описание кинетических вещей раз радужных больше нет они вводят в заблуждение

**Comment by Almat2** [comment]
Можеш вставить версию с дизбалансным где есть все радужные и потребления мало как отдельную от этого мода?

**Comment by MindustryDagger** [comment]
привет, данная версия должна быть в релизах

**Comment by Almat2** [comment]
Аа увидел спасибо я не так много пользуюсь гитхабом так что не знал:)

**Comment by Almat2** [comment]
Насчет потреблений там можно думаю попробовать сделать два вида генераторов те что открывают например тори без тория но потребляющий 3000 энергий или разные ресы ввиде пресса а дальше сделать уже более усовершественную версию которая иследуется за 3000 тория или больше но потребляющая только 580 энергий ведь не так и далеко до обычных залежей торий там останется пока откроеш усовершенственную версию

**Comment by Almat2** [comment]
И такое к каждому виду ресов если возможно

**Comment by Almat2** [comment]
Я не знаю как пользоваться гитхабом так что не знаю написать так чтобы было удобнее и не засорялось разной ненужной инфой

**Comment by Almat2** [comment]
Кста у тебя маломощьные генераторы меди и свинца с недочетами свинец не вырабатывается а медь бесплатный

**Comment by Almat2** [comment]
Им бы увеличить стоимость до 250 меди каждому и сделать скорость выработки до 0.20

**Comment by Almat2** [comment]
Мое дело предложить если нужны еще идеи пиши в дискорд имя пользователя: soktama

**Comment by Almat2** [comment]
На андройде и на пк версий на винде у криогенки ошибка с изображением написано oh no красным по белому
