### ISSUE TITLE
Ребаланс

### ISSUE THREAD

**Issue by XGUDLUDX** [MindustryDagger/VanillaPlus#2]
Слишком быстрый "Радужный конвеер" ну тоесть он и правда слишком быстрый мне кажется стоит повысить цену строительства в 10 раз потому что слишком дешёвый.
Тоже самая проблема с солнечными панелями а если точнее "Радужной солнечной панели" тут проблема не в цене строительства а скорее в производстве энергии ведь оно слишком большое от 1800 до 4800.

**Comment by MindustryDagger** [comment]
Я сам уже видел, скоро исправлю, но спасибо.
