### ISSUE TITLE
Проблемка

### ISSUE THREAD

**Issue by TheNickname99** [MindustryDagger/VanillaPlus#5]
Проблема с енергетическим заводом кремния. Просто поставьте его, и вы не сможете сломать его или контактировать с ним. Прошу также проверить другие блоки

**Comment by MindustryDagger** [comment]
Здравствуйте, @TheNickname99, скачайте мод ещё раз исправил, мод ещё а альфе, могут быть проблемы, поскольку код изменился, спасибо.
