### ISSUE TITLE
игра крашается на пк

### ISSUE THREAD

**Issue by spamexe** [MindustryDagger/VanillaPlus#8]
игра крашается после того как ты поставишь перекресток, и после этого нельзя зайти на сектор. проблма с титановым.ведь после титанового игра сразу крашается

**Comment by spamexe** [comment]
проблеме только с титановым. руина 5 секторов, исправь пж а то я уже почти всю ко панию заруинил

**Comment by MindustryDagger** [comment]
Должно помочь

**Comment by spamexe** [comment]
не рработает
![Снимок экрана 2022-09-16 133233](https://user-images.githubusercontent.com/101331223/190572139-571b0574-062a-434a-99ba-8767e1d13d49.png)

**Comment by MindustryDagger** [comment]
Отправь репорт сюда, я посмотрю

**Comment by MindustryDagger** [comment]
Да, вылетает, смотрю репорт У СЕБЯ

**Comment by MindustryDagger** [comment]
Починил, смотри

**Comment by spamexe** [comment]
Всё сработало. не вылетает
